// src/carsData.js
const newCars = [
  {
    id: 1,
    make: 'Toyota',
    model: 'Corolla',
    year: 2024,
    color: 'Grey',
    price: 20000,
    image: '/images/toyota corolla.png',
    engine: '1.8L 4-cylinder',
    fuelType: 'Petrol',
    transmission: 'CVT',
    features: [
      'Adaptive Cruise Control',
      'Lane Departure Warning',
      'Apple CarPlay',
      'Android Auto',
    ],
  },
  {
    id: 2,
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    color: 'Red',
    price: 22000,
    image: '/images/honda civic.png',
    engine: '2.0L 4-cylinder',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    features: [
      'Blind Spot Monitoring',
      'Heated Seats',
      'Sunroof',
      'LED Headlights',
    ],
  },
  {
    id: 3,
    make: 'Ford',
    model: 'Mustang',
    year: 2024,
    color: 'Blue',
    price: 35000,
    image: '/images/ford mustang.png',
    engine: '5.0L V8',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    features: [
      'Leather Seats',
      'Performance Exhaust',
      'Track Apps',
      'Brembo Brakes',
    ],
  },
  {
    id: 4,
    make: 'Tesla',
    model: 'Model S',
    year: 2022,
    color: 'Red',
    price: 80000,
    image: '/images/tesla model S.png',
    engine: 'Dual Motor AWD',
    fuelType: 'Electric',
    transmission: 'Automatic',
    features: [
      'Autopilot',
      '17-inch Touchscreen',
      'Over-the-Air Updates',
      'Premium Audio',
    ],
  },
  {
    id: 5,
    make: 'BMW',
    model: 'X5',
    year: 2024,
    color: 'Silver',
    price: 60000,
    image: '/images/bmw x5.png',
    engine: '3.0L 6-cylinder',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    features: [
      'Panoramic Sunroof',
      'Heated Steering Wheel',
      'Wireless Charging',
      'Adaptive Suspension',
    ],
  },
  {
    id: 6,
    make: 'Audi',
    model: 'A4',
    year: 2021,
    color: 'Red',
    price: 45000,
    image: '/images/audi a4.png',
    engine: '2.0L 4-cylinder',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    features: [
      'Virtual Cockpit',
      'Quattro AWD',
      'Bang & Olufsen Sound System',
      'LED Matrix Headlights',
    ],
  },
  {
    id: 7,
    make: 'Chevrolet',
    model: 'Camaro',
    year: 2022,
    color: 'Yellow',
    price: 40000,
    image: '/images/chevrolet camaro.png',
    engine: '6.2L V8',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    features: [
      'Heads-Up Display',
      'Performance Suspension',
      'Recaro Seats',
      'Dual Exhaust',
    ],
  },
  {
    id: 8,
    make: 'Porsche',
    model: '911',
    year: 2024,
    color: 'White',
    price: 120000,
    image: '/images/porsche 911.png',
    engine: '3.0L Twin-Turbo Flat-6',
    fuelType: 'Gasoline',
    transmission: 'PDK Automatic',
    features: [
      'Sport Chrono Package',
      'Active Suspension',
      'Carbon Fiber Roof',
      'Bose Surround Sound',
    ],
  },
  {
    id: 9,
    make: 'Mercedes-Benz',
    model: 'E-class',
    year: 2023,
    color: 'Black',
    price: 55000,
    image: '/images/E-class.png',
    engine: '3.0L Twin-Turbo Flat-6',
    fuelType: 'Gasoline',
    transmission: 'PDK Automatic',
    features: [
      'Dual Exhaust',
      'Active Suspension',
      'Carbon Fiber Roof',
      'Bose Surround Sound',
    ]
  }
]  
const usedCars = [
  {
    id: 10,
    make: 'Toyota',
    model: 'Camry',
    year: 2017,
    color: 'White',
    price: 15000,
    image: '/images/toyota camry.png',
    engine: '2.5L 4-cylinder',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    features: [
      'Lane Departure Warning',
      'Adaptive Cruise Control',
      'Apple CarPlay',
      'Android Auto',
    ],
  },
  {
    id: 11,
    make: 'Honda',
    model: 'Accord',
    year: 2014,
    color: 'Blue',
    price: 18000,
    image: '/images/honda accord.png',
    engine: '1.5L 4-cylinder',
    fuelType: 'Petrol',
    transmission: 'CVT',
    features: [
      'Blind Spot Monitoring',
      'Heated Seats',
      'Sunroof',
      'LED Headlights',
    ],
  },
  {
    id: 12,
    make: 'Ford',
    model: 'Fusion',
    year: 2015,
    color: 'Black',
    price: 12000,
    image: '/images/ford fusion.png',
    engine: '2.0L 4-cylinder',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    features: [
      'Leather Seats',
      'Heated Steering Wheel',
      'Adaptive Cruise Control',
      'Lane Keep Assist',
    ],
  },
  {
    id: 13,
    make: 'Tesla',
    model: 'Model 3',
    year: 2017,
    color: 'Silver',
    price: 35000,
    image: '/images/tesla model 3.png',
    engine: 'Dual Motor AWD',
    fuelType: 'Electric',
    transmission: 'Automatic',
    features: [
      'Autopilot',
      'Full Self-Driving',
      'Over-the-Air Updates',
      'Premium Connectivity',
    ],
  },
  {
    id: 14,
    make: 'BMW',
    model: '3 Series',
    year: 2016,
    color: 'Grey',
    price: 25000,
    image: '/images/bmw 3 series.png',
    engine: '2.0L 4-cylinder',
    fuelType: 'Diesel', 
    transmission: 'Automatic',
    features: [
      'Blind Spot Monitoring',
      'Heated Seats',
      'Sunroof',
      'LED Headlights',
    ]
  }
];
export { newCars, usedCars };
